version: '2'
services:
    easysettle-app:
        image: easysettle
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://easysettle-postgresql:5432/easySettle
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    easysettle-postgresql:
        extends:
            file: postgresql.yml
            service: easysettle-postgresql
